collections:
  tags:
    output: true
    permalink: /tags/:name/

permalink: /:categories/:year/:month/:day/:title:output_ext

markdown: kramdown
highlighter: rouge
baseurl: "/blog"
url: "https://elfaidi-ghassen.github.io"
